### ISSUE TITLE
MismatchedInputException from apparently good manifest

### ISSUE THREAD

**Issue by awagner-mainz** [intranda/goobi-iiif-downloader#1]
Dear team,

I was trying to download images for this work from the British Library: http://access.bl.uk/item/viewer/ark:/81055/vdc_100026327668.0x000001

but goob-iiif-downloader (downloaded, compiled and packaged today, 2020-03-16) raised the following error:

```
⏚ [:~/Temp/salamanca/bilder_f_qc/W0098] 1 $ java -jar ~/Temp/temp/vcs/goobi-iiif-downloader/target/goobi-iiif-downloader-1.1.0.jar -d=. -m=https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100026327668.0x000001/manifest.json
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
/ Receiving IIIF manifest...com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `de.intranda.api.iiif.presentation.content.ImageContent` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('https://www.bl.uk/images/bl_logo_100.gif')
 at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 94, column: 10] (through reference chain: de.intranda.api.iiif.presentation.Manifest["logo"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1032)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:371)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:323)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1373)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:171)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070)
	at de.intranda.iiif.downloader.IIIFDownloaderMain.getManifest(IIIFDownloaderMain.java:311)
	at de.intranda.iiif.downloader.IIIFDownloaderMain.call(IIIFDownloaderMain.java:101)
	at de.intranda.iiif.downloader.IIIFDownloaderMain.call(IIIFDownloaderMain.java:48)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1701)
	at picocli.CommandLine.access$900(CommandLine.java:146)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2059)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2026)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1893)
	at picocli.CommandLine.execute(CommandLine.java:1822)
	at de.intranda.iiif.downloader.IIIFDownloaderMain.main(IIIFDownloaderMain.java:87)
```
I don't really have a good idea of what is going on, but maybe iiif-downloader cannot cope with the the BL sets up its manifests, in particular the "logo" field... Can you do anything about it? Can I?

PS. The same holds for other manifests, e.g. https://api.bl.uk/metadata/iiif/ark:/81055/vdc_100048438354.0x000001/manifest.json

**Comment by opaetzel** [comment]
Hi there,

yes this was a problem with de-serializing the IIIF manifest there. As we only use about 5% of the manifest, I changed the code to work with the JSON structure directly. If you try compiling and running the current master, it should work.

**Comment by awagner-mainz** [comment]
yes, it's working now. Thanks a million!
